### ISSUE TITLE
libpcre.so.3 dependency error on CentOS

### ISSUE THREAD

**Issue by mileswhen** [konclude/Konclude#17]
Dear Team,

I'm running into the following error on Linux CentOS:

```
Konclude: error while loading shared libraries: libpcre.so.3: cannot open shared object file: No such file or directory
```

I've checked and I seem to have PCRE installed. Would appreciate to get your thoughts on this.

Thank you

**Comment by andreas-steigmiller** [comment]
Thanks for the report (and sorry for the late reply). You may want to try the docker version (Konclude-v0.7.0-1138-Linux-Docker-Compiled-x64-GCC4.8.4-Static-Qt5.12.10.zip), which has hardly any dependencies. Otherwise you can try to add the missing library to the library path with a command as follows:

`$export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/lib:$LD_LIBRARY_PATH`,

where you may want to adapt `/lib/x86_64-linux-gnu/lib` to the directory of the PCRE lib. Other than that, I don't really know why the library cannot be located on your system. You may want to check `ldd Konclude`, which should retrun something as follows (to see whether/which libraries are resolved):
```
	linux-vdso.so.1 =>  (0x00007ffcd5fb9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5625624000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5625420000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f56251fe000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f5624f8d000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f5624c7c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5624a5f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f562467b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5624372000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f562415a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5623d90000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f562583e000)
```

**Comment by mileswhen** [comment]
Ah brilliant, thanks for the detailed answer. Using the docker version works!
